CREATE TABLE IF NOT EXISTS AIDecision (
  id TEXT PRIMARY KEY,
  deviceId TEXT NOT NULL,
  userId TEXT NOT NULL,
  recommendation TEXT NOT NULL,
  reasoning TEXT NOT NULL,
  confidence REAL NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (deviceId) REFERENCES Device(id) ON DELETE CASCADE,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);
