CREATE TABLE IF NOT EXISTS User (
  id TEXT PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  name TEXT NOT NULL,
  role TEXT DEFAULT 'BUYER',
  avatar TEXT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SellerProfile (
  id TEXT PRIMARY KEY,
  userId TEXT UNIQUE NOT NULL,
  storeName TEXT NOT NULL,
  businessId TEXT,
  description TEXT,
  rating REAL DEFAULT 0.0,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Device (
  id TEXT PRIMARY KEY,
  brand TEXT NOT NULL,
  model TEXT NOT NULL,
  releaseYear INTEGER NOT NULL,
  category TEXT NOT NULL,
  specifications TEXT DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS DeviceListing (
  id TEXT PRIMARY KEY,
  deviceId TEXT NOT NULL,
  sellerId TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  price REAL NOT NULL,
  condition TEXT DEFAULT 'REFURBISHED_EXCELLENT',
  status TEXT DEFAULT 'ACTIVE',
  images TEXT DEFAULT '[]',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (deviceId) REFERENCES Device(id) ON DELETE RESTRICT,
  FOREIGN KEY (sellerId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DigitalPassport (
  id TEXT PRIMARY KEY,
  listingId TEXT UNIQUE NOT NULL,
  serialNumber TEXT NOT NULL,
  originalPurchaseDate DATETIME,
  history TEXT DEFAULT '[]',
  repairs TEXT DEFAULT '[]',
  verified BOOLEAN DEFAULT 0,
  verifiedAt DATETIME,
  verifiedBy TEXT,
  FOREIGN KEY (listingId) REFERENCES DeviceListing(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SecondLifeScore (
  id TEXT PRIMARY KEY,
  deviceId TEXT UNIQUE NOT NULL,
  score INTEGER NOT NULL,
  breakdown TEXT DEFAULT '{}',
  lastCalculated DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (deviceId) REFERENCES Device(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS AIRecommendation (
  id TEXT PRIMARY KEY,
  userId TEXT NOT NULL,
  listingId TEXT NOT NULL,
  score REAL NOT NULL,
  reasoning TEXT,
  type TEXT DEFAULT 'SIMILAR_ITEM',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE,
  FOREIGN KEY (listingId) REFERENCES DeviceListing(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Order" (
  id TEXT PRIMARY KEY,
  buyerId TEXT NOT NULL,
  listingId TEXT NOT NULL,
  amount REAL NOT NULL,
  status TEXT DEFAULT 'PENDING',
  paymentIntentId TEXT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (buyerId) REFERENCES User(id) ON DELETE RESTRICT,
  FOREIGN KEY (listingId) REFERENCES DeviceListing(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS Review (
  id TEXT PRIMARY KEY,
  orderId TEXT UNIQUE NOT NULL,
  rating INTEGER NOT NULL,
  comment TEXT NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (orderId) REFERENCES "Order"(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SustainabilityRecord (
  id TEXT PRIMARY KEY,
  deviceId TEXT UNIQUE NOT NULL,
  co2SavedKg REAL NOT NULL,
  eWasteAvoidedKg REAL NOT NULL,
  calculatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (deviceId) REFERENCES Device(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Notification (
  id TEXT PRIMARY KEY,
  userId TEXT NOT NULL,
  type TEXT DEFAULT 'SYSTEM',
  message TEXT NOT NULL,
  read BOOLEAN DEFAULT 0,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Cart (
  id TEXT PRIMARY KEY,
  userId TEXT UNIQUE NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CartItem (
  id TEXT PRIMARY KEY,
  cartId TEXT NOT NULL,
  listingId TEXT UNIQUE NOT NULL,
  quantity INTEGER DEFAULT 1,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (cartId) REFERENCES Cart(id) ON DELETE CASCADE,
  FOREIGN KEY (listingId) REFERENCES DeviceListing(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Warranty (
  id TEXT PRIMARY KEY,
  orderId TEXT UNIQUE NOT NULL,
  duration INTEGER DEFAULT 12,
  status TEXT DEFAULT 'ACTIVE',
  expiresAt DATETIME NOT NULL,
  terms TEXT NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (orderId) REFERENCES "Order"(id) ON DELETE CASCADE
);
\nCREATE TABLE IF NOT EXISTS AuditLog (
  id TEXT PRIMARY KEY,
  userId TEXT NOT NULL,
  action TEXT NOT NULL,
  entity TEXT NOT NULL,
  entityId TEXT,
  details TEXT,
  ipAddress TEXT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);
\nCREATE TABLE IF NOT EXISTS Review (
  id TEXT PRIMARY KEY,
  orderId TEXT UNIQUE NOT NULL,
  rating INTEGER NOT NULL,
  comment TEXT NOT NULL,
  sellerReply TEXT,
  flagged BOOLEAN DEFAULT FALSE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (orderId) REFERENCES "Order"(id) ON DELETE CASCADE
);
\nCREATE TABLE IF NOT EXISTS Notification (
  id TEXT PRIMARY KEY,
  userId TEXT NOT NULL,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  link TEXT,
  read BOOLEAN DEFAULT FALSE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);
\nCREATE TABLE IF NOT EXISTS AIDecision (
  id TEXT PRIMARY KEY,
  deviceId TEXT NOT NULL,
  userId TEXT NOT NULL,
  recommendation TEXT NOT NULL,
  reasoning TEXT NOT NULL,
  confidence REAL NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (deviceId) REFERENCES Device(id) ON DELETE CASCADE,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);
