CREATE TABLE IF NOT EXISTS Review (
  id TEXT PRIMARY KEY,
  orderId TEXT UNIQUE NOT NULL,
  rating INTEGER NOT NULL,
  comment TEXT NOT NULL,
  sellerReply TEXT,
  flagged BOOLEAN DEFAULT FALSE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (orderId) REFERENCES "Order"(id) ON DELETE CASCADE
);
